api_platform:
    messenger:
        enabled: true
    metadata_backward_compatibility_layer: false
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/json', 'application/merge-patch+json']
        jsonld: ['application/ld+json']
    swagger:
        versions: [3]
