knpu_oauth2_client:
    clients:
        # configure your clients as described here: https://github.com/knpuniversity/oauth2-client-bundle#configuration
        facebook:
            type: facebook
            client_id: '%env(OAUTH_FACEBOOK_ID)%'
            client_secret: '%env(OAUTH_FACEBOOK_SECRET)%'
            redirect_route: login_facebook_check
            redirect_params: { }
            graph_api_version: v11.0
        google:
            type: google
            client_id: '%env(resolve:OAUTH_GOOGLE_ID)%'
            client_secret: '%env(resolve:OAUTH_GOOGLE_SECRET)%'
            redirect_route: login_google_check
            redirect_params: { }